[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
staking = "9G9s8fbeD7Q2kzS3tWeqbSDsEAkoERjThGqvcDgmVytG"

[programs.localnet]
even_odd_game = "AE4H2WjxmL8HKkefPffGbFYa5w97MgDVtnJG2UdCzX6x"
presale = "HzSvVixk8DzPE3wwL1UgAGWV5krBVKRUpxFwdqn72hAv"
staking = "9G9s8fbeD7Q2kzS3tWeqbSDsEAkoERjThGqvcDgmVytG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
init-staking = "node_modules/.bin/ts-node scripts/staking.initialize.ts"
test = "node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = "test-ledger"
rpc_port = 8899
