name: Test and Build Anchor

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          dir: 'anchor'

      - uses: metadaoproject/setup-anchor@v2
        with:
          anchor-version: '0.30.1'
          node-version: '20'
          solana-cli-version: '1.18.9'

      - name: Generate new keypair
        run: solana-keygen new --no-bip39-passphrase

      - name: Set solana target cluster to local
        run: solana config set --url http://localhost:8899

      - name: Check solana config
        run: solana config get

      - name: Run build program
        run: |
          cd anchor
          anchor build
        shell: bash

      - name: Run test
        run: |
          cd anchor
          anchor test
        shell: bash
